language: python
python:
  - "2.7"

before_install:

install:
  - wget https://github.com/twatteyne/smartmeshsdk/archive/master.zip 
  - unzip master.zip
  - pwd
  - ls
  - pip install -r requirements.txt

script:
  - python -m pytest tests/
