language: python
python:
  - "2.7"

before_install:
  - wget https://github.com/twatteyne/smartmeshsdk/archive/master.zip

install:
  - pwd
  - ls
  - pip install -r requirements.txt --use-mirrors

script:
  - python -m pytest tests/
